"""
training.py — CTDE Multi-Agent Path Planning
Algorithm: QMIX-inspired (shared actor networks + central mixing critic)

Architecture:
  - Each agent has a shared Actor (policy network)
  - Central Critic (mixing network) uses global state + all Q-values
  - Parameter sharing: all agents share one Actor weight set
  - Replay buffer stores full episodes (global state, joint obs, joint actions, joint rewards)

Run:
  python training.py
  → saves model to  models/actor.pt
  → saves metrics to models/training_metrics.npy
"""

import os, time, random, collections
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from environment import MultiAgentGridEnv

os.makedirs("models", exist_ok=True)

# ─────────────────────────── Hyper-parameters ──────────────────────────── #

N_AGENTS     = 4
N_EPISODES   = 3000
BATCH_SIZE   = 64
BUFFER_SIZE  = 10_000
GAMMA        = 0.99
LR_ACTOR     = 3e-4
LR_CRITIC    = 3e-4
EPS_START    = 1.0
EPS_END      = 0.05
EPS_DECAY    = 2500      # episodes to decay over
TAU          = 0.005     # soft-update rate for target network
UPDATE_EVERY = 4         # steps between gradient updates
HIDDEN       = 128
SEED         = 42

torch.manual_seed(SEED)
np.random.seed(SEED)
random.seed(SEED)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {DEVICE}")

# ────────────────────────────── Networks ───────────────────────────────── #

class ActorNet(nn.Module):
    """Shared policy: obs → Q-values for each action (DQN-style)."""
    def __init__(self, obs_size, n_actions, hidden=HIDDEN):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(obs_size, hidden), nn.ReLU(),
            nn.Linear(hidden, hidden),  nn.ReLU(),
            nn.Linear(hidden, n_actions)
        )

    def forward(self, x):
        return self.net(x)


class MixingNet(nn.Module):
    """
    QMIX mixing network:
      Inputs : agent Q-values (n_agents,) + global state
      Output : scalar total Q
    Weights of mixing layers are generated by hypernetworks conditioned on
    global state, ensuring monotonicity (weights are non-negative).
    """
    def __init__(self, n_agents, global_state_size, hidden=64):
        super().__init__()
        self.n_agents = n_agents
        # Hyper-net weights for first mixing layer (n_agents → hidden)
        self.hyper_w1 = nn.Linear(global_state_size, n_agents * hidden)
        self.hyper_b1 = nn.Linear(global_state_size, hidden)
        # Hyper-net weights for second mixing layer (hidden → 1)
        self.hyper_w2 = nn.Linear(global_state_size, hidden)
        self.hyper_b2 = nn.Sequential(
            nn.Linear(global_state_size, hidden), nn.ReLU(),
            nn.Linear(hidden, 1)
        )
        self.hidden = hidden

    def forward(self, agent_qs, state):
        """
        agent_qs : (B, n_agents)
        state    : (B, global_state_size)
        """
        B = agent_qs.size(0)
        # First layer
        w1 = torch.abs(self.hyper_w1(state)).view(B, self.n_agents, self.hidden)
        b1 = self.hyper_b1(state).view(B, 1, self.hidden)
        x  = F.elu(torch.bmm(agent_qs.unsqueeze(1), w1) + b1)   # (B,1,hidden)
        # Second layer
        w2 = torch.abs(self.hyper_w2(state)).view(B, self.hidden, 1)
        b2 = self.hyper_b2(state).view(B, 1, 1)
        q_tot = (torch.bmm(x, w2) + b2).squeeze(-1).squeeze(-1)  # (B,)
        return q_tot


# ────────────────────────────── Replay Buffer ──────────────────────────── #

Transition = collections.namedtuple(
    "Transition",
    ["obs", "global_state", "actions", "rewards",
     "next_obs", "next_global_state", "dones"]
)

class ReplayBuffer:
    def __init__(self, capacity):
        self.buf = collections.deque(maxlen=capacity)

    def push(self, *args):
        self.buf.append(Transition(*args))

    def sample(self, k):
        return random.sample(self.buf, k)

    def __len__(self):
        return len(self.buf)


# ─────────────────────────────── Agent ─────────────────────────────────── #

class CTDEAgent:
    def __init__(self, obs_size, n_actions, n_agents, global_state_size):
        self.obs_size   = obs_size
        self.n_actions  = n_actions
        self.n_agents   = n_agents

        # Actor (shared — one set of weights for all agents)
        self.actor        = ActorNet(obs_size, n_actions).to(DEVICE)
        self.actor_target = ActorNet(obs_size, n_actions).to(DEVICE)
        self.actor_target.load_state_dict(self.actor.state_dict())

        # Central critic (mixing network)
        self.mixer        = MixingNet(n_agents, global_state_size).to(DEVICE)
        self.mixer_target = MixingNet(n_agents, global_state_size).to(DEVICE)
        self.mixer_target.load_state_dict(self.mixer.state_dict())

        self.opt_actor  = optim.Adam(self.actor.parameters(),  lr=LR_ACTOR)
        self.opt_critic = optim.Adam(
            list(self.actor.parameters()) + list(self.mixer.parameters()),
            lr=LR_CRITIC)

        self.buffer = ReplayBuffer(BUFFER_SIZE)
        self.epsilon = EPS_START
        self.step_count = 0

    # ── action selection ─────────────────────────────────────────────── #

    def select_actions(self, obs_list, explore=True):
        actions = []
        for obs in obs_list:
            if explore and random.random() < self.epsilon:
                actions.append(random.randrange(self.n_actions))
            else:
                with torch.no_grad():
                    t = torch.FloatTensor(obs).unsqueeze(0).to(DEVICE)
                    q = self.actor(t)
                    actions.append(int(q.argmax(dim=1).item()))
        return actions

    # ── training step ────────────────────────────────────────────────── #

    def update(self):
        if len(self.buffer) < BATCH_SIZE:
            return None

        batch = self.buffer.sample(BATCH_SIZE)

        # ── unpack & tensorize ──────────────────────────────────────── #
        # obs / next_obs: each is list of (n_agents, obs_size)
        obs_b  = torch.FloatTensor(np.array([t.obs         for t in batch])).to(DEVICE)  # (B,N,obs)
        nobs_b = torch.FloatTensor(np.array([t.next_obs    for t in batch])).to(DEVICE)
        gs_b   = torch.FloatTensor(np.array([t.global_state      for t in batch])).to(DEVICE)
        ngs_b  = torch.FloatTensor(np.array([t.next_global_state for t in batch])).to(DEVICE)
        act_b  = torch.LongTensor( np.array([t.actions     for t in batch])).to(DEVICE)  # (B,N)
        rew_b  = torch.FloatTensor(np.array([t.rewards     for t in batch])).to(DEVICE)  # (B,N)
        done_b = torch.FloatTensor(np.array([t.dones       for t in batch])).to(DEVICE)  # (B,N)

        B, N = obs_b.shape[0], self.n_agents

        # ── current Q values ────────────────────────────────────────── #
        # Reshape: (B*N, obs_size) → forward → (B*N, n_actions)
        obs_flat  = obs_b.view(B*N, -1)
        q_all     = self.actor(obs_flat).view(B, N, self.n_actions)   # (B,N,A)
        q_chosen  = q_all.gather(2, act_b.unsqueeze(2)).squeeze(2)   # (B,N)

        q_tot = self.mixer(q_chosen, gs_b)   # (B,)

        # ── target Q values (Double DQN) ─────────────────────────────── #
        with torch.no_grad():
            nobs_flat    = nobs_b.view(B*N, -1)
            # use online net to select action, target net to evaluate
            next_q_online = self.actor(nobs_flat).view(B, N, self.n_actions)
            next_acts     = next_q_online.argmax(dim=2)                # (B,N)
            next_q_target = self.actor_target(nobs_flat).view(B, N, self.n_actions)
            next_q_chosen = next_q_target.gather(2, next_acts.unsqueeze(2)).squeeze(2)

            # reward & done per-agent → sum for mixing
            reward_sum = rew_b.sum(dim=1)   # (B,)
            done_any   = done_b.max(dim=1).values  # (B,)

            q_tot_target_next = self.mixer_target(next_q_chosen, ngs_b)
            y = reward_sum + GAMMA * q_tot_target_next * (1 - done_any)

        loss = F.mse_loss(q_tot, y)

        self.opt_critic.zero_grad()
        loss.backward()
        nn.utils.clip_grad_norm_(
            list(self.actor.parameters()) + list(self.mixer.parameters()), 10.0)
        self.opt_critic.step()

        # ── soft update targets ─────────────────────────────────────── #
        self._soft_update(self.actor, self.actor_target)
        self._soft_update(self.mixer, self.mixer_target)

        return loss.item()

    @staticmethod
    def _soft_update(net, target):
        for p, tp in zip(net.parameters(), target.parameters()):
            tp.data.copy_(TAU * p.data + (1 - TAU) * tp.data)

    def decay_epsilon(self, episode):
        self.epsilon = max(EPS_END,
                           EPS_START - (EPS_START - EPS_END) * episode / EPS_DECAY)

    def save(self, path="models/actor.pt"):
        torch.save(self.actor.state_dict(), path)
        print(f"Saved actor -> {path}")

    def load(self, path="models/actor.pt"):
        self.actor.load_state_dict(torch.load(path, map_location=DEVICE))
        self.actor_target.load_state_dict(self.actor.state_dict())
        print(f"Loaded actor <- {path}")


# ──────────────────────────────── Training loop ─────────────────────────── #

def train():
    env   = MultiAgentGridEnv(n_agents=N_AGENTS, seed=SEED)
    agent = CTDEAgent(
        obs_size          = env.obs_size,
        n_actions         = env.n_actions,
        n_agents          = N_AGENTS,
        global_state_size = env.global_state_size,
    )

    metrics = {
        "episode_reward": [],
        "goals_reached" : [],
        "episode_steps" : [],
        "loss"          : [],
        "epsilon"       : [],
    }

    t_start    = time.time()
    loss_accum = []

    print(f"\n{'='*55}")
    print(f"  CTDE QMIX Training  |  {N_AGENTS} agents  |  {N_EPISODES} episodes")
    print(f"{'='*55}\n")

    for ep in range(N_EPISODES):
        obs        = env.reset()
        gs         = env.get_global_state()
        ep_reward  = 0.0
        step_count = 0

        while True:
            actions    = agent.select_actions(obs, explore=True)
            next_obs, rewards, dones, global_done, info = env.step(actions)
            next_gs    = env.get_global_state()

            agent.buffer.push(
                np.array(obs),
                gs,
                np.array(actions),
                np.array(rewards),
                np.array(next_obs),
                next_gs,
                np.array(dones, dtype=np.float32),
            )

            obs        = next_obs
            gs         = next_gs
            ep_reward += sum(rewards)
            step_count += 1

            if step_count % UPDATE_EVERY == 0:
                l = agent.update()
                if l is not None:
                    loss_accum.append(l)

            if global_done:
                break

        agent.decay_epsilon(ep)

        metrics["episode_reward"].append(ep_reward)
        metrics["goals_reached"].append(info["reached_goal"])
        metrics["episode_steps"].append(step_count)
        metrics["loss"].append(np.mean(loss_accum) if loss_accum else 0.0)
        metrics["epsilon"].append(agent.epsilon)
        loss_accum.clear()

        if (ep+1) % 100 == 0:
            recent = slice(-100, None)
            avg_r  = np.mean(metrics["episode_reward"][recent])
            avg_g  = np.mean(metrics["goals_reached"][recent])
            avg_s  = np.mean(metrics["episode_steps"][recent])
            avg_l  = np.mean(metrics["loss"][recent])
            elapsed = time.time() - t_start
            print(f"Ep {ep+1:4d}/{N_EPISODES} | "
                  f"AvgRew={avg_r:7.1f} | "
                  f"Goals={avg_g:.2f}/{N_AGENTS} | "
                  f"Steps={avg_s:.1f} | "
                  f"Loss={avg_l:.4f} | "
                  f"ε={agent.epsilon:.3f} | "
                  f"{elapsed:.0f}s")

    agent.save("models/actor.pt")
    np.save("models/training_metrics.npy", metrics)
    print("\nTraining complete. Plotting metrics …")
    _plot_metrics(metrics)


def _plot_metrics(metrics):
    fig, axes = plt.subplots(2, 2, figsize=(12, 8))
    fig.suptitle("CTDE QMIX Training Metrics", fontsize=14, fontweight="bold")

    def smooth(x, w=50):
        return np.convolve(x, np.ones(w)/w, mode="valid")

    ep = np.arange(len(metrics["episode_reward"]))

    ax = axes[0, 0]
    ax.plot(ep, metrics["episode_reward"], alpha=0.3, color="steelblue")
    if len(ep) >= 50:
        ax.plot(ep[49:], smooth(metrics["episode_reward"]), color="steelblue", lw=2)
    ax.set_title("Episode Reward"); ax.set_xlabel("Episode"); ax.set_ylabel("Total Reward")
    ax.grid(alpha=0.3)

    ax = axes[0, 1]
    ax.plot(ep, metrics["goals_reached"], alpha=0.3, color="green")
    if len(ep) >= 50:
        ax.plot(ep[49:], smooth(metrics["goals_reached"]), color="green", lw=2)
    ax.axhline(N_AGENTS, ls="--", color="red", alpha=0.5, label="Max")
    ax.set_title("Goals Reached / Episode"); ax.set_xlabel("Episode"); ax.set_ylabel("# Goals")
    ax.legend(); ax.grid(alpha=0.3)

    ax = axes[1, 0]
    ax.plot(ep, metrics["episode_steps"], alpha=0.3, color="orange")
    if len(ep) >= 50:
        ax.plot(ep[49:], smooth(metrics["episode_steps"]), color="orange", lw=2)
    ax.set_title("Steps per Episode"); ax.set_xlabel("Episode"); ax.set_ylabel("Steps")
    ax.grid(alpha=0.3)

    ax = axes[1, 1]
    valid_loss = [(i, l) for i, l in enumerate(metrics["loss"]) if l > 0]
    if valid_loss:
        xi, yi = zip(*valid_loss)
        ax.plot(xi, yi, alpha=0.4, color="purple")
        if len(xi) >= 50:
            sm = smooth(list(yi))
            ax.plot(list(xi)[49:len(xi)-len(xi)+len(sm)+49], sm, color="purple", lw=2)
    ax.set_title("Training Loss"); ax.set_xlabel("Episode"); ax.set_ylabel("MSE Loss")
    ax.grid(alpha=0.3)

    plt.tight_layout()
    plt.savefig("models/training_metrics.png", dpi=120)
    print("Saved -> models/training_metrics.png")
    plt.close()


if __name__ == "__main__":
    train()
